### ISSUE TITLE
neon_build highjacks test binaries

### ISSUE THREAD

**Issue by Progdrasil** [neon-bindings/neon#732]
When running `cargo test` with the following setup, the `neon_build` setup highjacks the outputed binary for the test suite.

`Cargo.toml`
```toml
[package]
name = "my_lib"
version = "0.1.0"
authors = ["Rene Leveille"]
edition = "2018"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "my_lib"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.8.1"

[dependencies]
neon = { version = "0.8.1", features = ["napi-latest"], default-features = false 
```

`build.rs`
```rust
fn main() {
    neon_build::setup();
}
```

`lib.rs`
```rust
use neon::prelude::*;

fn hello_rust(mut cx: FunctionContext) -> JsResult<JsString> {
    Ok(cx.string("Hello From Rust"))
}

register_module!(mut m, { m.export_function("helloRust", hello_rust) });

#[cfg(test)]
mod tests {
    #[test]
    fn sample_test() {
        assert_eq!(super::hello_rust(), "Hello From Rust");
    }
}
```

When running this on a linux machine i get the following output:
```shell
$ cargo test
...
   Finished test [unoptimized + debuginfo] target(s) in 6.58s
     Running target/debug/deps/my_lib-45f1b6442c0168d3
error: test failed, to rerun pass '--lib'

Caused by:
  could not execute process `/home/rene/my_lib/target/debug/deps/my_lib-45f1b6442c0168d3` (never executed)
```

This is because [these lines](https://github.com/neon-bindings/neon/blob/56b3715d7bab3012247e867e247ed03e7788b2f4/crates/neon-build/src/napi/mod.rs#L23) in `neon_build::napi` overwrite the output for any of cargo's outputs
