### ISSUE TITLE
N-API module doesn't seem to be context-aware

### ISSUE THREAD

**Issue by arthrarnld** [neon-bindings/neon#748]
Hi team! 👋🏻 

I built a simple module using Neon with N-API to test the strange behaviour I'm getting.
The gist of it is: if I have two Node contexts running different code that imports the same
binary, I'd expect their `cx.global()`s to be isolated from one another, but it looks like that's
not the case.
The reason I expected that is this sentence in [Node's VM documentation](https://nodejs.org/api/vm.html#vm_vm_executing_javascript):
> The invoked code treats any property in the context like a global variable. Any changes to global variables caused by the invoked code are reflected in the context object.

Did I misunderstand it? Or am I forgetting something to make this work? Or could this
be a bug in Neon?
Below are the file contents of the project.

<details>
<summary><b>Cargo.toml</b></summary>

```toml
[package]
name = "ctx"
version = "0.1.0"
license = "MIT"
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "ctx"
crate-type = ["cdylib"]

[dependencies]
neon = {version = "0.8.2", default-features = false, features = ["napi-6"]}
```

</details>

<details>
<summary><b>native/src/lib.rs</b></summary>

```rust
use neon::prelude::*;

fn get(mut cx: FunctionContext) -> JsResult<JsValue> {
    cx.global().get(&mut cx, "foo")
}

fn set(mut cx: FunctionContext) -> JsResult<JsUndefined> {
    let val = cx.argument::<JsString>(0).unwrap();
    cx.global().set(&mut cx, "foo", val).unwrap();
    Ok(cx.undefined())
}

#[neon::main]
fn neon_main(mut cx: ModuleContext) -> NeonResult<()> {
    cx.export_function("set", set)?;
    cx.export_function("get", get)
}
```

</details>

<details>
<summary><b>lib/index.js</b></summary>

```javascript
const vm = require("vm");

const code1 = `
var addon = require('../native');
addon.set('value 1');
setTimeout(() => {
  console.log('Context 1: ' + addon.get());
}, 1000);
`;

const code2 = `
var addon = require('../native');
addon.set('value 2');
console.log('Context 2: ' + addon.get());
`;

vm.runInNewContext(code1, { setTimeout, require, console });
vm.runInNewContext(code2, { setTimeout, require, console });
```

</details>

I expected the output from `index.js` to be
```
Context 2: value 2
Context 1: value 1
```
but instead I get
```
Context 2: value 2
Context 1: value 2
```

Any help on this is much appreciated. :)
